// Action types for the app reducer
export const ACTIONS = {
  // User actions
  SET_USER: 'SET_USER',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  LOGOUT: 'LOGOUT',

  // Cart actions
  SET_CART: 'SET_CART',
  SET_CART_LOADING: 'SET_CART_LOADING',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
  UPDATE_CART_COUNT: 'UPDATE_CART_COUNT',

  // Books actions
  SET_BOOKS: 'SET_BOOKS',
  SET_FEATURED_BOOKS: 'SET_FEATURED_BOOKS',
  SET_BESTSELLERS: 'SET_BESTSELLERS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_BOOKS_LOADING: 'SET_BOOKS_LOADING',

  // Wishlist actions
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  SET_WISHLIST: 'SET_WISHLIST',

  // UI actions
  SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
  HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',
  SHOW_CART_MODAL: 'SHOW_CART_MODAL',
  HIDE_CART_MODAL: 'HIDE_CART_MODAL',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',

  // Search actions
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SET_SEARCHING: 'SET_SEARCHING'
};
